resources:
  pipelines:
  - pipeline: main
    source: pipeline_main

parameters:
  - name: azureServicePrincipal
    displayName: Azure Service Principal
    type: string
    default:  pan-firewall-dev-lab

variables:
- group: firewall-vars-1

stages:
- stages: create-subnet
  jobs:
    - job: testResourceGroup
      steps:
        - task: AzureCLI@2
          inputs:
            scriptType:  bash
            scriptLocation: inlineScript
            inlineScript: az group exists -n sfc-network-dev-rg- # test failure
            failOnStandardError:  true
    - job: deployTemplate
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: ${{ parameters.azureServicePrincipal }}
            action: 'Create Or Update Resource Group'
            resourceGroupName: sfc-$(subnetPrefix)-$(environment)-rg
            location: $(location)
            templateLocation: 'Linked artifact'
            csmFile: firewall.json
            csmParametersFile: firewall.parameters.json
            overrideParameters: #-adminPassword $(adminPassword) -bootstrapAccessKey $(bootstrapAccessKey)
            deploymentMode: 'Incremental'